aoshidoadmin:
    resource: "@AoshidoadminBundle/Resources/config/routing.yml"
    prefix:   /admin/

aoshidoweb:
    resource: "@AoshidowebBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"