aoshidoweb:
    resource: "@AoshidowebBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
        
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
