security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext #sha512

    role_hierarchy:
        ROLE_STUDENT:     ROLE_USER
        ROLE_TEACHER:     ROLE_STUDENT
        ROLE_ADMIN:       ROLE_TEACHER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SONATA_ADMIN: ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                failure_path: aoshidoweb_homepage
                login_path: /
            logout:       true
            anonymous:    true
            access_denied_url: /


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/users/, role: ROLE_ADMIN }
        - { path: ^/abms/, role: ROLE_STUDENT }