# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    dzango.twig.truncate_extension:
        class: Dzango\Twig\Extension\Truncate
        tags:
            - { name: twig.extension }

    fos_user.listener.flash:
        class: Aoshido\UserBundle\EventListener\FlashListener
        arguments: [@session,@translator]
        tags:
            - { name: kernel.event_subscriber }       

    fos_user.doctrine_registry:
        alias: doctrine