abms_index:
    path:     /
    defaults: { _controller: AoshidowebBundle:Abms:index }
    
abms_preguntas:
    path:     /preguntas
    defaults: { _controller: AoshidowebBundle:Preguntas:new }    
     
preguntas_disable:
    path:     /preguntas/disable/{idPregunta}
    defaults: { _controller: AoshidowebBundle:Preguntas:disable }

preguntas_edit:
    path:     /preguntas/edit/{idPregunta}
    defaults: { _controller: AoshidowebBundle:Preguntas:edit }

abms_temas:
    path:     /temas
    defaults: { _controller: AoshidowebBundle:Temas:new }    
    
temas_edit:
    path:     /temas/edit/{idTema}
    defaults: { _controller: AoshidowebBundle:Temas:edit }    

temas_disable:
    path:     /temas/disable/{idTema}
    defaults: { _controller: AoshidowebBundle:Temas:disable }    

abms_carreras:
    path:     /carreras
    defaults: { _controller: AoshidowebBundle:Carreras:new }    

carreras_edit:
    path:     /carreras/edit/{idCarrera}
    defaults: { _controller: AoshidowebBundle:Carreras:edit }    

carreras_disable:
    path:     /carreras/disable/{idCarrera}
    defaults: { _controller: AoshidowebBundle:Carreras:disable }    

carreras_desvincular_materia:
    path:     /carreras/edit/{idCarrera}/desvincular/{idMateria}
    defaults: { _controller: AoshidowebBundle:Carreras:desvincular }    
    
abms_materias:
    path:     /materias
    defaults: { _controller: AoshidowebBundle:Materias:new }    

materias_edit:
    path:     /materias/edit/{idMateria}
    defaults: { _controller: AoshidowebBundle:Materias:edit }    

materias_disable:
    path:     /materias/disable/{idMateria}
    defaults: { _controller: AoshidowebBundle:Materias:disable }    
    
respuestas_new:
    path:     /respuestas/{idPregunta}
    defaults: { _controller: AoshidowebBundle:Respuestas:new }    

respuestas_edit:
    path:     /respuestas/{idPregunta}/edit/{idRespuesta}
    defaults: { _controller: AoshidowebBundle:Respuestas:edit }    
    
respuestas_disable:
    path:     /respuestas/disable/{idRespuesta}
    defaults: { _controller: AoshidowebBundle:Respuestas:disable }    