abms_index:
    path:     /
    defaults: { _controller: AoshidowebBundle:Abms:index }
    
abms_preguntas:
    path:     /preguntas
    defaults: { _controller: AoshidowebBundle:Preguntas:new }    

abms_temas:
    path:     /temas
    defaults: { _controller: AoshidowebBundle:Temas:new }    
