abms_index:
    path:     /
    defaults: { _controller: AoshidowebBundle:Abms:index }
    
abms_preguntas:
    path:     /preguntas
    defaults: { _controller: AoshidowebBundle:Preguntas:new }    
    
preguntas_addMateria:
    path:     /preguntas/addMaterias
    defaults: { _controller: AoshidowebBundle:Preguntas:MateriasByCarrera }

preguntas_addTemas:
    path:     /preguntas/addTemas
    defaults: { _controller: AoshidowebBundle:Preguntas:TemasByMateria }
    
preguntas_disable:
    path:     /preguntas/disable/{idPregunta}
    defaults: { _controller: AoshidowebBundle:Preguntas:disable }

abms_temas:
    path:     /temas
    defaults: { _controller: AoshidowebBundle:Temas:new }    

abms_carreras:
    path:     /carreras
    defaults: { _controller: AoshidowebBundle:Carreras:new }    
    
abms_materias:
    path:     /materias
    defaults: { _controller: AoshidowebBundle:Materias:new }    
    
respuestas_new:
    path:     /respuestas/{idPregunta}
    defaults: { _controller: AoshidowebBundle:Respuestas:new }    
    
respuestas_disable:
    path:     /respuestas/disable/{idRespuesta}
    defaults: { _controller: AoshidowebBundle:Respuestas:disable }    