abms_index:
    path:     /
    defaults: { _controller: AoshidowebBundle:Abms:index }
    
abms_preguntas:
    path:     /preguntas
    defaults: { _controller: AoshidowebBundle:Preguntas:new }    

abms_temas:
    path:     /temas
    defaults: { _controller: AoshidowebBundle:Temas:new }    

abms_carreras:
    path:     /carreras
    defaults: { _controller: AoshidowebBundle:Carreras:new }    
    
abms_materias:
    path:     /materias
    defaults: { _controller: AoshidowebBundle:Materias:new }    