games_quiz:
    path:     /quiz
    defaults: { _controller: AoshidowebBundle:Games:quiz }

games_cards:
    path:     /cards
    defaults: { _controller: AoshidowebBundle:Games:cards }

games_challenge:
    path:     /challenge
    defaults: { _controller: AoshidowebBundle:Games:challenge }

games_challenge_new:
    path:     /challenge/newPregunta
    defaults: { _controller: AoshidowebBundle:Games:newPregunta }

games_settings:
    path:     /settings
    defaults: { _controller: AoshidowebBundle:Games:settings }
    
games_resultados:
    path:     /resultados
    defaults: { _controller: AoshidowebBundle:Games:resultados }
    methods:  [POST, PATCH]
    
games_resultados_show:
    path:     /show
    defaults: { _controller: AoshidowebBundle:Games:show }

