games_quiz:
    path:     /quiz
    defaults: { _controller: AoshidowebBundle:Games:quiz }

games_settings:
    path:     /settings
    defaults: { _controller: AoshidowebBundle:Games:settings }