games_quiz:
    path:     /quiz
    defaults: { _controller: AoshidowebBundle:Games:quiz }

games_cards:
    path:     /cards
    defaults: { _controller: AoshidowebBundle:Games:cards }

games_settings:
    path:     /settings
    defaults: { _controller: AoshidowebBundle:Games:settings }
