users_index:
    path:     /
    defaults: { _controller: AoshidowebBundle:User:index }

users_promote:
    path:     /promote/{idUser}
    defaults: { _controller: AoshidowebBundle:User:promote }