<?php

namespace Aoshido\webBundle\Entity;

/**
 * Carrerarepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Carrerarepository extends \Doctrine\ORM\EntityRepository
{
}
