aoshidoweb_homepage:
    path:     /
    defaults: { _controller: AoshidowebBundle:Default:index }

aoshidoweb_bio:
    path:     /bio
    defaults: { _controller: AoshidowebBundle:Default:bio }
    
abms:
    resource: "@AoshidowebBundle/Resources/config/routing/abms.yml"
    prefix:   /abms
