aoshidoweb_homepage:
    path:     /
    defaults: { _controller: AoshidowebBundle:Default:index }
    #path:     /{_locale}
    #requirements:
    #    _locale: en|es|jp
    
aoshidoweb_bio:
    path:     /bio
    defaults: { _controller: AoshidowebBundle:Default:bio }
    
aoshidoweb_faq:
    path:     /faq
    defaults: { _controller: AoshidowebBundle:Default:faq }
    
aoshidoweb_bugs:
    path:     /bugs
    defaults: { _controller: AoshidowebBundle:Bugs:index }

aoshidoweb_bugsplat:
    path:     /bugsplat
    defaults: { _controller: AoshidowebBundle:Bugs:bugsplat }
    
preguntas_addMateria:
    path:     /preguntas/addMaterias
    defaults: { _controller: AoshidowebBundle:Preguntas:MateriasByCarrera }
    methods:  [POST, PATCH]

preguntas_addTemas:
    path:     /preguntas/addTemas
    defaults: { _controller: AoshidowebBundle:Preguntas:TemasByMateria }
    methods:  [POST, PATCH]
    
abms:
    resource: "@AoshidowebBundle/Resources/config/routing/abms.yml"
    prefix:   /abms
    
games:
    resource: "@AoshidowebBundle/Resources/config/routing/games.yml"
    prefix:   /games

users:
    resource: "@AoshidowebBundle/Resources/config/routing/users.yml"
    prefix:   /users
