aoshidoweb_homepage:
    path:     /
    defaults: { _controller: AoshidowebBundle:Default:index }

aoshidoweb_bio:
    path:     /bio
    defaults: { _controller: AoshidowebBundle:Default:bio }
    
aoshidoweb_bugs:
    path:     /bugs
    defaults: { _controller: AoshidowebBundle:Bugs:index }
    
abms:
    resource: "@AoshidowebBundle/Resources/config/routing/abms.yml"
    prefix:   /abms
    
games:
    resource: "@AoshidowebBundle/Resources/config/routing/games.yml"
    prefix:   /games
