services:
#    aoshidoweb.example:
#        class: Aoshido\webBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    admin.carrera:
        class: Aoshido\webBundle\Admin\CarreraAdmin
        arguments: [~, Aoshido\webBundle\Entity\Carrera, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Carrera
              group: "Academico"
              
    admin.materia:
        class: Aoshido\webBundle\Admin\MateriaAdmin
        arguments: [~, Aoshido\webBundle\Entity\Materia, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Materia
              group: "Academico"
              
    admin.tema:
        class: Aoshido\webBundle\Admin\TemaAdmin
        arguments: [~, Aoshido\webBundle\Entity\Tema, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Tema
              group: "Academico"
    
    admin.user:
        class: Aoshido\webBundle\Admin\UserAdmin
        arguments: [~, Aoshido\UserBundle\Entity\User, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: User
              group: "Soporte"
        
    admin.bug:
        class: Aoshido\webBundle\Admin\BugAdmin
        arguments: [~, Aoshido\webBundle\Entity\Bug, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Bug
              group: "Soporte"
              
    aoshido.stats.block:
        class: Aoshido\webBundle\Admin\blocks\StatsBlock
        arguments:
            - aoshido.stats.block
            - "@templating"
            - @doctrine.orm.entity_manager
        tags:
            - { name: sonata.block }
            
    aoshido.last_questions.block:
        class: Aoshido\webBundle\Admin\blocks\LastQuestionsBlock
        arguments:
            - aoshido.lsat_questions.block
            - "@templating"
            - @doctrine.orm.entity_manager
        tags:
            - { name: sonata.block }