services:
    bug.listener:
        class: Aoshido\webBundle\EventListener\BugMailer
        arguments:
            templating: "@twig"
            mailer: "@mailer" 
            token_storage: "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: postUpdate , lazy: true }   

#Sonata Blocks
    admin.carrera:
        class: Aoshido\webBundle\Admin\CarreraAdmin
        arguments: [~, Aoshido\webBundle\Entity\Carrera, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Carrera
              group: "Academico"
              
    admin.materia:
        class: Aoshido\webBundle\Admin\MateriaAdmin
        arguments: [~, Aoshido\webBundle\Entity\Materia, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Materia
              group: "Academico"
              
    admin.tema:
        class: Aoshido\webBundle\Admin\TemaAdmin
        arguments: [~, Aoshido\webBundle\Entity\Tema, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Tema
              group: "Academico"
    
    admin.user:
        class: Aoshido\webBundle\Admin\UserAdmin
        arguments: [~, Aoshido\UserBundle\Entity\User, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: User
              group: "Soporte"
        
    admin.bug:
        class: Aoshido\webBundle\Admin\BugAdmin
        arguments: [~, Aoshido\webBundle\Entity\Bug, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Bug
              group: "Soporte"
              
    aoshido.stats.block:
        class: Aoshido\webBundle\Admin\blocks\StatsBlock
        arguments:
            - aoshido.stats.block
            - "@templating"
            - @doctrine.orm.entity_manager
        tags:
            - { name: sonata.block }
            
    aoshido.last_questions.block:
        class: Aoshido\webBundle\Admin\blocks\LastQuestionsBlock
        arguments:
            - aoshido.last_questions.block
            - "@templating"
            - @doctrine.orm.entity_manager
        tags:
            - { name: sonata.block }
            
    aoshido.creative_users.block:
        class: Aoshido\webBundle\Admin\blocks\MostCreativeUsersBlock
        arguments:
            - aoshido.creative_users.block
            - "@templating"
            - @doctrine.orm.entity_manager
        tags:
            - { name: sonata.block }