services:
#    aoshidoweb.example:
#        class: Aoshido\webBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    admin.carrera:
        class: Aoshido\webBundle\Admin\CarreraAdmin
        arguments: [~, Aoshido\webBundle\Entity\Carrera, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Carrera
              group: "Academico"
    
    admin.user:
        class: Aoshido\webBundle\Admin\UserAdmin
        arguments: [~, Aoshido\UserBundle\Entity\User, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: User
              group: "Soporte"
        
    admin.bug:
        class: Aoshido\webBundle\Admin\BugAdmin
        arguments: [~, Aoshido\webBundle\Entity\Bug, ~]
        tags:
            - name: sonata.admin 
              manager_type: orm
              label: Bug
              group: "Soporte"