services:
#    aoshidoweb.example:
#        class: Aoshido\webBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    service_disabler:
        class:        Aoshido\webBundle\Services\ServiceDisabler
        arguments:    [@doctrine.orm.default_entity_manager]